name: TSC check CI

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: codeberg-tiny
    steps:
    - uses: actions/checkout@v4
    - name: install node v22
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - name: npm i
      run: npm i
    - name: npm run tsc
      run: npm run tsc --noEmit
